// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: init_game.sql

package db

import (
	"context"
)

const addApocalypse = `-- name: AddApocalypse :exec
INSERT INTO apocalypses (val)
VALUES ($1)
`

func (q *Queries) AddApocalypse(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addApocalypse, val)
	return err
}

const addPlace = `-- name: AddPlace :exec
INSERT INTO places (val)
VALUES ($1)
`

func (q *Queries) AddPlace(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addPlace, val)
	return err
}

const addResource = `-- name: AddResource :exec
INSERT INTO resources (val)
VALUES ($1)
`

func (q *Queries) AddResource(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addResource, val)
	return err
}

const addRoom = `-- name: AddRoom :exec
INSERT INTO rooms (val)
VALUES ($1)
`

func (q *Queries) AddRoom(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addRoom, val)
	return err
}
