// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: init_character.sql

package db

import (
	"context"
)

const addAbility = `-- name: AddAbility :exec
INSERT INTO abilities (val)
VALUES ($1)
`

func (q *Queries) AddAbility(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addAbility, val)
	return err
}

const addBody = `-- name: AddBody :exec
INSERT INTO bodies (val)
VALUES ($1)
`

func (q *Queries) AddBody(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addBody, val)
	return err
}

const addHealth = `-- name: AddHealth :exec
INSERT INTO health (val)
VALUES ($1)
`

func (q *Queries) AddHealth(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addHealth, val)
	return err
}

const addHobby = `-- name: AddHobby :exec
INSERT INTO hobbies (val)
VALUES ($1)
`

func (q *Queries) AddHobby(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addHobby, val)
	return err
}

const addInfo = `-- name: AddInfo :exec
INSERT INTO info (val)
VALUES ($1)
`

func (q *Queries) AddInfo(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addInfo, val)
	return err
}

const addItem = `-- name: AddItem :exec
INSERT INTO items (val)
VALUES ($1)
`

func (q *Queries) AddItem(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addItem, val)
	return err
}

const addJob = `-- name: AddJob :exec
INSERT INTO jobs (val)
VALUES ($1)
`

func (q *Queries) AddJob(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addJob, val)
	return err
}

const addPhobia = `-- name: AddPhobia :exec
INSERT INTO phobias (val)
VALUES ($1)
`

func (q *Queries) AddPhobia(ctx context.Context, val string) error {
	_, err := q.db.ExecContext(ctx, addPhobia, val)
	return err
}
